# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/meizu/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter 16th,$(TARGET_DEVICE)),)

endif
